### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by tetutetu214** [tetutetu214/bprotospace-31782#5]
自身のProtoSpaceのURL
https://protospace-31782.herokuapp.com/

**Comment by TECHCAMP555** [comment]
tetutetu214さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・他のユーザーが投稿したプロトタイプの編集ページにURLを直接入力して遷移しようとすると、トップページにリダイレクトされる
→編集ページへ遷移されてしまいます。

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by tetutetu214** [comment]
ご指摘箇所についての修正を致しました
ご確認ください。

GitHubのリモートリポジトリにプッシュしたのち、再度確認依頼を提出のためデプロイはしておりません

**Comment by tech-oa** [comment]
tetutetu214さん、ご提出ありがとうございます！お待たせいたしました。
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・他のユーザーが投稿したプロトタイプの編集ページにURLを直接入力して遷移しようとすると、トップページにリダイレクトされる
→編集ページへ遷移されてしまいます。
**→修正が確認できず、同様に編集ページに遷移されてしまいます。**

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by tetutetu214** [comment]
ご指摘箇所についての修正を致しました
ご確認ください。

デプロイ致しました

**Comment by tech-oa** [comment]
tetutetu214さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、修正されておりました！
他機能も全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。
